# Env

In [1]:
import easydict
import random

import matplotlib.pyplot as plt
import numpy as np
import torch

In [2]:
# 환경 설정
args = easydict.EasyDict({
    # random seed value
    "seed": 1234,
    # CPU 또는 GPU 사용여부 결정
    "device": torch.device("cuda" if torch.cuda.is_available() else "cpu")
})

print(args)

{'seed': 1234, 'device': device(type='cpu')}


In [3]:
# random seed 설정
random.seed(args.seed)
np.random.seed(args.seed)
torch.manual_seed(args.seed)
torch.cuda.manual_seed_all(args.seed)

# 행렬 A

In [4]:
# A 행렬 선언
A = np.random.randint(-9, 10, (5, 4)) / 10
A = torch.tensor(A)
print(A)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)


# Element Wise Sum

In [5]:
# B 행렬 합
B = np.random.randint(-9, 10, (5, 4)) / 10
B = torch.tensor(B)

print(A)
print(B)
print(A + B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)
tensor([[-0.2000,  0.2000, -0.9000,  0.0000],
        [ 0.2000,  0.7000, -0.6000, -0.7000],
        [ 0.3000, -0.8000,  0.2000,  0.2000],
        [ 0.8000,  0.5000, -0.2000,  0.1000],
        [ 0.2000,  0.5000,  0.8000,  0.4000]], dtype=torch.float64)
tensor([[ 0.4000, -0.1000, -0.6000,  0.6000],
        [ 1.0000,  0.7000, -0.4000, -0.4000],
        [ 1.0000, -1.2000,  0.9000,  0.2000],
        [ 1.4000,  1.4000,  0.5000,  0.4000],
        [-0.2000, -0.2000,  0.5000, -0.2000]], dtype=torch.float64)


## Boradcasting $(m \times n) + (m \times 1)$

In [6]:
# B 행렬 Boradcasting 합
B = np.random.randint(-9, 10, (5, 1)) / 10
B = torch.tensor(B)

print(A)
print(B)
print(A + B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)
tensor([[-0.9000],
        [ 0.3000],
        [-0.4000],
        [ 0.8000],
        [-0.4000]], dtype=torch.float64)
tensor([[-0.3000, -1.2000, -0.6000, -0.3000],
        [ 1.1000,  0.3000,  0.5000,  0.6000],
        [ 0.3000, -0.8000,  0.3000, -0.4000],
        [ 1.4000,  1.7000,  1.5000,  1.1000],
        [-0.8000, -1.1000, -0.7000, -1.0000]], dtype=torch.float64)


In [7]:
# B 행렬 열복사 후 합
B1 = B.repeat(1, 4)

print(B1)
print(A + B1)

tensor([[-0.9000, -0.9000, -0.9000, -0.9000],
        [ 0.3000,  0.3000,  0.3000,  0.3000],
        [-0.4000, -0.4000, -0.4000, -0.4000],
        [ 0.8000,  0.8000,  0.8000,  0.8000],
        [-0.4000, -0.4000, -0.4000, -0.4000]], dtype=torch.float64)
tensor([[-0.3000, -1.2000, -0.6000, -0.3000],
        [ 1.1000,  0.3000,  0.5000,  0.6000],
        [ 0.3000, -0.8000,  0.3000, -0.4000],
        [ 1.4000,  1.7000,  1.5000,  1.1000],
        [-0.8000, -1.1000, -0.7000, -1.0000]], dtype=torch.float64)


## Boradcasting $(m \times n) + (1 \times n)$

In [8]:
# B 행렬 Boradcasting 합
B = np.random.randint(-9, 10, (1, 4)) / 10
B = torch.tensor(B)

print(A)
print(B)
print(A + B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)
tensor([[ 0.4000,  0.7000,  0.0000, -0.1000]], dtype=torch.float64)
tensor([[ 1.0000,  0.4000,  0.3000,  0.5000],
        [ 1.2000,  0.7000,  0.2000,  0.2000],
        [ 1.1000,  0.3000,  0.7000, -0.1000],
        [ 1.0000,  1.6000,  0.7000,  0.2000],
        [ 0.0000,  0.0000, -0.3000, -0.7000]], dtype=torch.float64)


In [9]:
# B 행렬 행복사 후 합
B1 = B.repeat(5, 1)

print(B1)
print(A + B1)

tensor([[ 0.4000,  0.7000,  0.0000, -0.1000],
        [ 0.4000,  0.7000,  0.0000, -0.1000],
        [ 0.4000,  0.7000,  0.0000, -0.1000],
        [ 0.4000,  0.7000,  0.0000, -0.1000],
        [ 0.4000,  0.7000,  0.0000, -0.1000]], dtype=torch.float64)
tensor([[ 1.0000,  0.4000,  0.3000,  0.5000],
        [ 1.2000,  0.7000,  0.2000,  0.2000],
        [ 1.1000,  0.3000,  0.7000, -0.1000],
        [ 1.0000,  1.6000,  0.7000,  0.2000],
        [ 0.0000,  0.0000, -0.3000, -0.7000]], dtype=torch.float64)


## Boradcasting $(m \times n) + (1 \times 1)$

In [10]:
# B 행렬 Boradcasting 합
B = np.random.randint(-9, 10, (1, 1)) / 10
B = torch.tensor(B)

print(A)
print(B)
print(A + B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)
tensor([[0.3000]], dtype=torch.float64)
tensor([[ 0.9000,  0.0000,  0.6000,  0.9000],
        [ 1.1000,  0.3000,  0.5000,  0.6000],
        [ 1.0000, -0.1000,  1.0000,  0.3000],
        [ 0.9000,  1.2000,  1.0000,  0.6000],
        [-0.1000, -0.4000,  0.0000, -0.3000]], dtype=torch.float64)


In [11]:
# B 행렬 행과 열 복사 후 합
B1 = B.repeat(5, 4)

print(B1)
print(A + B1)

tensor([[0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000]], dtype=torch.float64)
tensor([[ 0.9000,  0.0000,  0.6000,  0.9000],
        [ 1.1000,  0.3000,  0.5000,  0.6000],
        [ 1.0000, -0.1000,  1.0000,  0.3000],
        [ 0.9000,  1.2000,  1.0000,  0.6000],
        [-0.1000, -0.4000,  0.0000, -0.3000]], dtype=torch.float64)


# Element Wise Product

In [12]:
# B 행렬 element wise product
B = np.random.randint(-9, 10, (5, 4)) / 10
B = torch.tensor(B)

print(A)
print(B)
print(A * B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)
tensor([[-0.3000,  0.3000,  0.6000,  0.8000],
        [ 0.9000,  0.5000, -0.7000, -0.4000],
        [ 0.4000, -0.3000, -0.2000, -0.5000],
        [-0.6000, -0.4000,  0.5000,  0.6000],
        [ 0.6000,  0.6000, -0.7000,  0.1000]], dtype=torch.float64)
tensor([[-0.1800, -0.0900,  0.1800,  0.4800],
        [ 0.7200,  0.0000, -0.1400, -0.1200],
        [ 0.2800,  0.1200, -0.1400, -0.0000],
        [-0.3600, -0.3600,  0.3500,  0.1800],
        [-0.2400, -0.4200,  0.2100, -0.0600]], dtype=torch.float64)


## Boradcasting $(m \times n) + (m \times 1)$

In [13]:
# B 행렬 Boradcasting element wise product
B = np.random.randint(-9, 10, (5, 1)) / 10
B = torch.tensor(B)

print(A)
print(B)
print(A * B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)
tensor([[-0.5000],
        [ 0.9000],
        [-0.2000],
        [ 0.2000],
        [ 0.5000]], dtype=torch.float64)
tensor([[-0.3000,  0.1500, -0.1500, -0.3000],
        [ 0.7200,  0.0000,  0.1800,  0.2700],
        [-0.1400,  0.0800, -0.1400, -0.0000],
        [ 0.1200,  0.1800,  0.1400,  0.0600],
        [-0.2000, -0.3500, -0.1500, -0.3000]], dtype=torch.float64)


In [14]:
# B 행렬 열복사 후 element wise product
B1 = B.repeat(1, 4)

print(B1)
print(A * B1)

tensor([[-0.5000, -0.5000, -0.5000, -0.5000],
        [ 0.9000,  0.9000,  0.9000,  0.9000],
        [-0.2000, -0.2000, -0.2000, -0.2000],
        [ 0.2000,  0.2000,  0.2000,  0.2000],
        [ 0.5000,  0.5000,  0.5000,  0.5000]], dtype=torch.float64)
tensor([[-0.3000,  0.1500, -0.1500, -0.3000],
        [ 0.7200,  0.0000,  0.1800,  0.2700],
        [-0.1400,  0.0800, -0.1400, -0.0000],
        [ 0.1200,  0.1800,  0.1400,  0.0600],
        [-0.2000, -0.3500, -0.1500, -0.3000]], dtype=torch.float64)


## Boradcasting $(m \times n) + (1 \times n)$

In [15]:
# B 행렬 Boradcasting element wise product
B = np.random.randint(-9, 10, (1, 4)) / 10
B = torch.tensor(B)

print(A)
print(B)
print(A * B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)
tensor([[ 0.9000,  0.0000, -0.9000, -0.7000]], dtype=torch.float64)
tensor([[ 0.5400, -0.0000, -0.2700, -0.4200],
        [ 0.7200,  0.0000, -0.1800, -0.2100],
        [ 0.6300, -0.0000, -0.6300, -0.0000],
        [ 0.5400,  0.0000, -0.6300, -0.2100],
        [-0.3600, -0.0000,  0.2700,  0.4200]], dtype=torch.float64)


In [16]:
# B 행렬 행복사 후 element wise product
B1 = B.repeat(5, 1)

print(B1)
print(A * B1)

tensor([[ 0.9000,  0.0000, -0.9000, -0.7000],
        [ 0.9000,  0.0000, -0.9000, -0.7000],
        [ 0.9000,  0.0000, -0.9000, -0.7000],
        [ 0.9000,  0.0000, -0.9000, -0.7000],
        [ 0.9000,  0.0000, -0.9000, -0.7000]], dtype=torch.float64)
tensor([[ 0.5400, -0.0000, -0.2700, -0.4200],
        [ 0.7200,  0.0000, -0.1800, -0.2100],
        [ 0.6300, -0.0000, -0.6300, -0.0000],
        [ 0.5400,  0.0000, -0.6300, -0.2100],
        [-0.3600, -0.0000,  0.2700,  0.4200]], dtype=torch.float64)


## Boradcasting $(m \times n) + (1 \times 1)$

In [17]:
# B 행렬 Boradcasting element wise product
B = np.random.randint(-9, 10, (1, 1)) / 10
B = torch.tensor(B)

print(A)
print(B)
print(A * B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)
tensor([[-0.8000]], dtype=torch.float64)
tensor([[-0.4800,  0.2400, -0.2400, -0.4800],
        [-0.6400, -0.0000, -0.1600, -0.2400],
        [-0.5600,  0.3200, -0.5600, -0.0000],
        [-0.4800, -0.7200, -0.5600, -0.2400],
        [ 0.3200,  0.5600,  0.2400,  0.4800]], dtype=torch.float64)


In [18]:
# B 행렬 행과 열 복사 후 합
B1 = B.repeat(5, 4)

print(B1)
print(A + B1)

tensor([[-0.8000, -0.8000, -0.8000, -0.8000],
        [-0.8000, -0.8000, -0.8000, -0.8000],
        [-0.8000, -0.8000, -0.8000, -0.8000],
        [-0.8000, -0.8000, -0.8000, -0.8000],
        [-0.8000, -0.8000, -0.8000, -0.8000]], dtype=torch.float64)
tensor([[-0.2000, -1.1000, -0.5000, -0.2000],
        [ 0.0000, -0.8000, -0.6000, -0.5000],
        [-0.1000, -1.2000, -0.1000, -0.8000],
        [-0.2000,  0.1000, -0.1000, -0.5000],
        [-1.2000, -1.5000, -1.1000, -1.4000]], dtype=torch.float64)


# Matrix Multiplication

In [19]:
# B 행렬 matrix multiplication
B = np.random.randint(-9, 10, (4, 3)) / 10
B = torch.tensor(B)

print(A)
print(B)
print(torch.matmul(A, B))

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)
tensor([[ 0.9000,  0.8000, -0.2000],
        [-0.5000, -0.2000,  0.8000],
        [-0.9000,  0.0000,  0.9000],
        [ 0.0000, -0.8000,  0.5000]], dtype=torch.float64)
tensor([[ 0.4200,  0.0600,  0.2100],
        [ 0.5400,  0.4000,  0.1700],
        [ 0.2000,  0.6400,  0.1700],
        [-0.5400,  0.0600,  1.3800],
        [ 0.2600,  0.3000, -1.0500]], dtype=torch.float64)


In [20]:
# 직접계산
result = torch.zeros(A.size(0), B.size(-1))
for row in range(A.size(0)):
    for col in range(B.size(-1)):
        result[row][col] = torch.dot(A[row], B[:, col])

print(result)

tensor([[ 0.4200,  0.0600,  0.2100],
        [ 0.5400,  0.4000,  0.1700],
        [ 0.2000,  0.6400,  0.1700],
        [-0.5400,  0.0600,  1.3800],
        [ 0.2600,  0.3000, -1.0500]])


# Dot-product

In [26]:
# a, b 벡터 선언
a = np.random.randint(-9, 10, (5,)) / 10
a = torch.tensor(a)

b = np.random.randint(-9, 10, (5,)) / 10
b = torch.tensor(b)

print(a)
print(b)

tensor([ 0.4000,  0.2000,  0.6000,  0.7000, -0.9000], dtype=torch.float64)
tensor([ 0.8000, -0.9000,  0.8000,  0.0000, -0.6000], dtype=torch.float64)


In [30]:
# dot-product
print(torch.dot(a, b))

tensor(1.1600, dtype=torch.float64)


In [33]:
# element wise product and sum
c = a * b

print(c)
print(torch.sum(c))

tensor([ 0.3200, -0.1800,  0.4800,  0.0000,  0.5400], dtype=torch.float64)
tensor(1.1600, dtype=torch.float64)
