# Env

In [ ]:
import argparse
import random

import matplotlib.pyplot as plt
import numpy as np
import torch

In [ ]:
# 환경 설정
args = {
    # random seed value
    "seed": 1234,
    # CPU 또는 GPU 사용여부 결정
    "device": torch.device("cuda" if torch.cuda.is_available() else "cpu")
}
args = argparse.Namespace(**args)

print(args)

Namespace(device=device(type='cpu'), seed=1234)


In [ ]:
# random seed 설정
random.seed(args.seed)
np.random.seed(args.seed)
torch.manual_seed(args.seed)
torch.cuda.manual_seed_all(args.seed)

# 행렬 A

In [ ]:
# A 행렬 선언
A = np.random.randint(-9, 10, (5, 4)) / 10
A = torch.tensor(A)
print(A)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)


# Element Wise Sum

In [ ]:
# B 행렬 합
B = np.random.randint(-9, 10, (5, 4)) / 10
B = torch.tensor(B)

print(A)
print()
print(B)
print()
print(A + B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)

tensor([[ 0.8000,  0.0000,  0.6000, -0.1000],
        [-0.7000,  0.7000,  0.2000, -0.7000],
        [ 0.9000,  0.6000, -0.6000,  0.5000],
        [-0.7000, -0.5000, -0.8000,  0.1000],
        [-0.7000,  0.4000, -0.6000,  0.9000]], dtype=torch.float64)

tensor([[ 1.4000, -0.3000,  0.9000,  0.5000],
        [ 0.1000,  0.7000,  0.4000, -0.4000],
        [ 1.6000,  0.2000,  0.1000,  0.5000],
        [-0.1000,  0.4000, -0.1000,  0.4000],
        [-1.1000, -0.3000, -0.9000,  0.3000]], dtype=torch.float64)


## Boradcasting $(m \times n) + (m \times 1)$

In [ ]:
# B 행렬 Boradcasting 합
B = np.random.randint(-9, 10, (5, 1)) / 10
B = torch.tensor(B)

print(A)
print()
print(B)
print()
print(A + B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)

tensor([[ 0.3000],
        [-0.4000],
        [ 0.8000],
        [ 0.7000],
        [-0.1000]], dtype=torch.float64)

tensor([[ 0.9000,  0.0000,  0.6000,  0.9000],
        [ 0.4000, -0.4000, -0.2000, -0.1000],
        [ 1.5000,  0.4000,  1.5000,  0.8000],
        [ 1.3000,  1.6000,  1.4000,  1.0000],
        [-0.5000, -0.8000, -0.4000, -0.7000]], dtype=torch.float64)


In [ ]:
# B 행렬 열복사 후 합
B1 = B.repeat(1, 4)

print(B1)
print()
print(A + B1)

tensor([[ 0.3000,  0.3000,  0.3000,  0.3000],
        [-0.4000, -0.4000, -0.4000, -0.4000],
        [ 0.8000,  0.8000,  0.8000,  0.8000],
        [ 0.7000,  0.7000,  0.7000,  0.7000],
        [-0.1000, -0.1000, -0.1000, -0.1000]], dtype=torch.float64)

tensor([[ 0.9000,  0.0000,  0.6000,  0.9000],
        [ 0.4000, -0.4000, -0.2000, -0.1000],
        [ 1.5000,  0.4000,  1.5000,  0.8000],
        [ 1.3000,  1.6000,  1.4000,  1.0000],
        [-0.5000, -0.8000, -0.4000, -0.7000]], dtype=torch.float64)


## Boradcasting $(m \times n) + (1 \times n)$

In [ ]:
# B 행렬 Boradcasting 합
B = np.random.randint(-9, 10, (1, 4)) / 10
B = torch.tensor(B)

print(A)
print()
print(B)
print()
print(A + B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)

tensor([[0.4000, 0.2000, 0.6000, 0.7000]], dtype=torch.float64)

tensor([[ 1.0000, -0.1000,  0.9000,  1.3000],
        [ 1.2000,  0.2000,  0.8000,  1.0000],
        [ 1.1000, -0.2000,  1.3000,  0.7000],
        [ 1.0000,  1.1000,  1.3000,  1.0000],
        [ 0.0000, -0.5000,  0.3000,  0.1000]], dtype=torch.float64)


In [ ]:
# B 행렬 행복사 후 합
B1 = B.repeat(5, 1)

print(B1)
print()
print(A + B1)

tensor([[0.4000, 0.2000, 0.6000, 0.7000],
        [0.4000, 0.2000, 0.6000, 0.7000],
        [0.4000, 0.2000, 0.6000, 0.7000],
        [0.4000, 0.2000, 0.6000, 0.7000],
        [0.4000, 0.2000, 0.6000, 0.7000]], dtype=torch.float64)

tensor([[ 1.0000, -0.1000,  0.9000,  1.3000],
        [ 1.2000,  0.2000,  0.8000,  1.0000],
        [ 1.1000, -0.2000,  1.3000,  0.7000],
        [ 1.0000,  1.1000,  1.3000,  1.0000],
        [ 0.0000, -0.5000,  0.3000,  0.1000]], dtype=torch.float64)


## Boradcasting $(m \times n) + (1 \times 1)$

In [ ]:
# B 행렬 Boradcasting 합
B = np.random.randint(-9, 10, (1, 1)) / 10
B = torch.tensor(B)

print(A)
print()
print(B)
print()
print(A + B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)

tensor([[-0.9000]], dtype=torch.float64)

tensor([[-0.3000, -1.2000, -0.6000, -0.3000],
        [-0.1000, -0.9000, -0.7000, -0.6000],
        [-0.2000, -1.3000, -0.2000, -0.9000],
        [-0.3000,  0.0000, -0.2000, -0.6000],
        [-1.3000, -1.6000, -1.2000, -1.5000]], dtype=torch.float64)


In [ ]:
# B 행렬 행과 열 복사 후 합
B1 = B.repeat(5, 4)

print(B1)
print()
print(A + B1)

tensor([[-0.9000, -0.9000, -0.9000, -0.9000],
        [-0.9000, -0.9000, -0.9000, -0.9000],
        [-0.9000, -0.9000, -0.9000, -0.9000],
        [-0.9000, -0.9000, -0.9000, -0.9000],
        [-0.9000, -0.9000, -0.9000, -0.9000]], dtype=torch.float64)

tensor([[-0.3000, -1.2000, -0.6000, -0.3000],
        [-0.1000, -0.9000, -0.7000, -0.6000],
        [-0.2000, -1.3000, -0.2000, -0.9000],
        [-0.3000,  0.0000, -0.2000, -0.6000],
        [-1.3000, -1.6000, -1.2000, -1.5000]], dtype=torch.float64)


# Element Wise Product

In [ ]:
# B 행렬 element wise product
B = np.random.randint(-9, 10, (5, 4)) / 10
B = torch.tensor(B)

print(A)
print()
print(B)
print()
print(A * B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)

tensor([[ 0.8000, -0.9000,  0.8000,  0.0000],
        [-0.6000, -0.5000, -0.8000,  0.2000],
        [ 0.8000, -0.3000, -0.7000, -0.2000],
        [ 0.3000,  0.3000, -0.9000, -0.1000],
        [ 0.6000,  0.4000,  0.4000,  0.0000]], dtype=torch.float64)

tensor([[ 0.4800,  0.2700,  0.2400,  0.0000],
        [-0.4800, -0.0000, -0.1600,  0.0600],
        [ 0.5600,  0.1200, -0.4900, -0.0000],
        [ 0.1800,  0.2700, -0.6300, -0.0300],
        [-0.2400, -0.2800, -0.1200, -0.0000]], dtype=torch.float64)


## Boradcasting $(m \times n) + (m \times 1)$

In [ ]:
# B 행렬 Boradcasting element wise product
B = np.random.randint(-9, 10, (5, 1)) / 10
B = torch.tensor(B)

print(A)
print()
print(B)
print()
print(A * B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)

tensor([[ 0.6000],
        [-0.5000],
        [-0.2000],
        [-0.2000],
        [ 0.8000]], dtype=torch.float64)

tensor([[ 0.3600, -0.1800,  0.1800,  0.3600],
        [-0.4000, -0.0000, -0.1000, -0.1500],
        [-0.1400,  0.0800, -0.1400, -0.0000],
        [-0.1200, -0.1800, -0.1400, -0.0600],
        [-0.3200, -0.5600, -0.2400, -0.4800]], dtype=torch.float64)


In [ ]:
# B 행렬 열복사 후 element wise product
B1 = B.repeat(1, 4)

print(B1)
print()
print(A * B1)

tensor([[ 0.6000,  0.6000,  0.6000,  0.6000],
        [-0.5000, -0.5000, -0.5000, -0.5000],
        [-0.2000, -0.2000, -0.2000, -0.2000],
        [-0.2000, -0.2000, -0.2000, -0.2000],
        [ 0.8000,  0.8000,  0.8000,  0.8000]], dtype=torch.float64)

tensor([[ 0.3600, -0.1800,  0.1800,  0.3600],
        [-0.4000, -0.0000, -0.1000, -0.1500],
        [-0.1400,  0.0800, -0.1400, -0.0000],
        [-0.1200, -0.1800, -0.1400, -0.0600],
        [-0.3200, -0.5600, -0.2400, -0.4800]], dtype=torch.float64)


## Boradcasting $(m \times n) + (1 \times n)$

In [ ]:
# B 행렬 Boradcasting element wise product
B = np.random.randint(-9, 10, (1, 4)) / 10
B = torch.tensor(B)

print(A)
print()
print(B)
print()
print(A * B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)

tensor([[-0.2000,  0.9000, -0.4000, -0.7000]], dtype=torch.float64)

tensor([[-0.1200, -0.2700, -0.1200, -0.4200],
        [-0.1600,  0.0000, -0.0800, -0.2100],
        [-0.1400, -0.3600, -0.2800, -0.0000],
        [-0.1200,  0.8100, -0.2800, -0.2100],
        [ 0.0800, -0.6300,  0.1200,  0.4200]], dtype=torch.float64)


In [ ]:
# B 행렬 행복사 후 element wise product
B1 = B.repeat(5, 1)

print(B1)
print()
print(A * B1)

tensor([[-0.2000,  0.9000, -0.4000, -0.7000],
        [-0.2000,  0.9000, -0.4000, -0.7000],
        [-0.2000,  0.9000, -0.4000, -0.7000],
        [-0.2000,  0.9000, -0.4000, -0.7000],
        [-0.2000,  0.9000, -0.4000, -0.7000]], dtype=torch.float64)

tensor([[-0.1200, -0.2700, -0.1200, -0.4200],
        [-0.1600,  0.0000, -0.0800, -0.2100],
        [-0.1400, -0.3600, -0.2800, -0.0000],
        [-0.1200,  0.8100, -0.2800, -0.2100],
        [ 0.0800, -0.6300,  0.1200,  0.4200]], dtype=torch.float64)


## Boradcasting $(m \times n) + (1 \times 1)$

In [ ]:
# B 행렬 Boradcasting element wise product
B = np.random.randint(-9, 10, (1, 1)) / 10
B = torch.tensor(B)

print(A)
print()
print(B)
print()
print(A * B)

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)

tensor([[0.9000]], dtype=torch.float64)

tensor([[ 0.5400, -0.2700,  0.2700,  0.5400],
        [ 0.7200,  0.0000,  0.1800,  0.2700],
        [ 0.6300, -0.3600,  0.6300,  0.0000],
        [ 0.5400,  0.8100,  0.6300,  0.2700],
        [-0.3600, -0.6300, -0.2700, -0.5400]], dtype=torch.float64)


In [ ]:
# B 행렬 행과 열 복사 후 합
B1 = B.repeat(5, 4)

print(B1)
print()
print(A + B1)

tensor([[0.9000, 0.9000, 0.9000, 0.9000],
        [0.9000, 0.9000, 0.9000, 0.9000],
        [0.9000, 0.9000, 0.9000, 0.9000],
        [0.9000, 0.9000, 0.9000, 0.9000],
        [0.9000, 0.9000, 0.9000, 0.9000]], dtype=torch.float64)

tensor([[1.5000, 0.6000, 1.2000, 1.5000],
        [1.7000, 0.9000, 1.1000, 1.2000],
        [1.6000, 0.5000, 1.6000, 0.9000],
        [1.5000, 1.8000, 1.6000, 1.2000],
        [0.5000, 0.2000, 0.6000, 0.3000]], dtype=torch.float64)


# Matrix Multiplication

In [ ]:
# B 행렬 matrix multiplication
B = np.random.randint(-9, 10, (4, 3)) / 10
B = torch.tensor(B)

print(A)
print()
print(B)
print()
print(torch.matmul(A, B))

tensor([[ 0.6000, -0.3000,  0.3000,  0.6000],
        [ 0.8000,  0.0000,  0.2000,  0.3000],
        [ 0.7000, -0.4000,  0.7000,  0.0000],
        [ 0.6000,  0.9000,  0.7000,  0.3000],
        [-0.4000, -0.7000, -0.3000, -0.6000]], dtype=torch.float64)

tensor([[-0.3000, -0.1000,  0.8000],
        [ 0.0000,  0.6000,  0.2000],
        [ 0.3000, -0.6000,  0.1000],
        [ 0.2000, -0.7000, -0.1000]], dtype=torch.float64)

tensor([[ 3.0000e-02, -8.4000e-01,  3.9000e-01],
        [-1.2000e-01, -4.1000e-01,  6.3000e-01],
        [-1.3323e-17, -7.3000e-01,  5.5000e-01],
        [ 9.0000e-02, -1.5000e-01,  7.0000e-01],
        [-9.0000e-02,  2.2000e-01, -4.3000e-01]], dtype=torch.float64)


In [ ]:
# 직접계산
result = torch.zeros(A.size(0), B.size(-1))
for row in range(A.size(0)):
    for col in range(B.size(-1)):
        result[row][col] = torch.dot(A[row], B[:, col])

print(result)

tensor([[ 0.0300, -0.8400,  0.3900],
        [-0.1200, -0.4100,  0.6300],
        [ 0.0000, -0.7300,  0.5500],
        [ 0.0900, -0.1500,  0.7000],
        [-0.0900,  0.2200, -0.4300]])


# Dot-product

In [ ]:
# a, b 벡터 선언
a = np.random.randint(-9, 10, (5,)) / 10
a = torch.tensor(a)

b = np.random.randint(-9, 10, (5,)) / 10
b = torch.tensor(b)

print(a)
print()
print(b)

tensor([-0.8000,  0.5000, -0.5000,  0.1000, -0.6000], dtype=torch.float64)

tensor([ 0.8000,  0.6000, -0.9000,  0.4000,  0.7000], dtype=torch.float64)


In [ ]:
# dot-product
print(torch.dot(a, b))

tensor(-0.1600, dtype=torch.float64)


In [ ]:
# element wise product and sum
c = a * b

print(c)
print()
print(torch.sum(c))

tensor([-0.6400,  0.3000,  0.4500,  0.0400, -0.4200], dtype=torch.float64)

tensor(-0.2700, dtype=torch.float64)
